### ISSUE TITLE
Any plans to replicate more than just repo content?

### ISSUE THREAD

**Issue by nneul** [samrocketman/gitlab-mirrors#67]
I'd like to easily spin up a purely read-only copy of a gitlab instance and keep it _semi_ current with content from the primary - including users,groups, membership/permissions, etc. (i.e. 12-24 hours delayed is fine) - something that could be used for pre-fetching repo commits from a local "cache" for efficiency or initial clones, but doing all pushes to remote.  

It looks like your tool would take care of all of the repo content level portion, but not anything with the users/permissions/etc. or secondary project level content/settings/etc. 

Any ideas or suggestions on this?

**Comment by samrocketman** [comment]
There's no plans to expand the scope of mirroring beyond source repositories.  The intent behind this project was to provide source mirroring of projects that are used, but not maintained, by your org.  e.g. your production releases depend on third party sources but instead of relying on the internet mirroring them in-house.

What you describe would probably be better served using database and filesystem replication so that multiple copies of the entire gitlab instance can be replicated at another location.  Again, not really in the scope or intent of this project.
